#!/usr/bin/env bash
set -Eeuo pipefail

umask 077

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
PROJECT_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd -P)"
ENV_FILE="${PROJECT_DIR}/.env"

usage() {
  echo "Usage: $0 ADMIN_EMAIL" >&2
  echo "Creates .env, provisions the control role, migrates, and starts the stack." >&2
}

if [[ $# -ne 1 || ! "$1" =~ ^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$ ]]; then
  usage
  exit 64
fi

for command in docker openssl; do
  if ! command -v "${command}" >/dev/null 2>&1; then
    echo "Required command not found: ${command}" >&2
    exit 69
  fi
done

if ! docker compose version >/dev/null 2>&1; then
  echo "Docker Compose v2 is required." >&2
  exit 69
fi

if [[ -e "${ENV_FILE}" ]]; then
  echo "Refusing to overwrite existing ${ENV_FILE}." >&2
  echo "Back it up or remove it explicitly, then run this script again." >&2
  exit 73
fi

private_key_file="$(mktemp "${TMPDIR:-/tmp}/nuvopic-jwt-key.XXXXXX")"
cleanup() {
  rm -f -- "${private_key_file}"
}
trap cleanup EXIT

openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:3072 \
  -out "${private_key_file}" >/dev/null 2>&1

postgres_admin_password="$(openssl rand -hex 32)"
control_database_password="$(openssl rand -hex 32)"
better_auth_secret="$(openssl rand -hex 32)"
directory_token="$(openssl rand -hex 32)"
settings_kek="$(openssl rand -hex 32)"
key_id="nuvopic-managed-$(date -u +%Y-%m-%d)"
private_key_pem="$(awk '{printf "%s\\\\n", $0}' "${private_key_file}")"

{
  printf '%s\n' \
    '# Generated by scripts/bootstrap.sh. Do not commit or share this file.' \
    'PUBLIC_ORIGIN=https://nuvopic.app' \
    'NUVOPIC_SITE_ADDRESS=nuvopic.app' \
    'LOG_LEVEL=info' \
    'POSTGRES_ADMIN_USER=nuvopic_admin' \
    "POSTGRES_ADMIN_PASSWORD=${postgres_admin_password}" \
    'CONTROL_DATABASE_NAME=nuvopic_control' \
    'CONTROL_DATABASE_USER=nuvopic_control' \
    "CONTROL_DATABASE_PASSWORD=${control_database_password}" \
    "BETTER_AUTH_SECRET=${better_auth_secret}" \
    "MANAGED_WORKSPACE_DIRECTORY_TOKEN=${directory_token}" \
    "SETTINGS_KEK=${settings_kek}" \
    'MANAGED_JWT_AUDIENCE=nuvopic' \
    "MANAGED_JWT_KEY_ID=${key_id}" \
    'MANAGED_JWT_TTL_SECONDS=300'
  printf 'MANAGED_JWT_PRIVATE_KEY_PEM="%s"\n' "${private_key_pem}"
  printf 'PLATFORM_ADMIN_EMAILS=%s\n' "$1"
  printf '%s\n' \
    'PROCESSING_MODE=modal' \
    'BATCH_GPU_PROVIDER=vastai' \
    '# Add credentials for the selected GPU providers before processing photos.'
} >"${ENV_FILE}"
chmod 600 "${ENV_FILE}"

cd -- "${PROJECT_DIR}"
docker compose up -d postgres

echo "Waiting for PostgreSQL to become healthy..."
for _ in {1..60}; do
  if docker compose exec -T postgres pg_isready \
    -U nuvopic_admin -d nuvopic_control >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

if ! docker compose exec -T postgres pg_isready \
  -U nuvopic_admin -d nuvopic_control >/dev/null 2>&1; then
  echo "PostgreSQL did not become ready within 120 seconds." >&2
  exit 70
fi

docker compose exec -T postgres psql \
  --set=ON_ERROR_STOP=1 \
  --set=control_user=nuvopic_control \
  --set=control_password="${control_database_password}" \
  --set=control_database=nuvopic_control \
  -U nuvopic_admin -d postgres <<'SQL'
SELECT format('CREATE ROLE %I LOGIN PASSWORD %L', :'control_user', :'control_password')
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = :'control_user') \gexec
SELECT format('ALTER ROLE %I WITH LOGIN PASSWORD %L', :'control_user', :'control_password') \gexec
SELECT format('ALTER DATABASE %I OWNER TO %I', :'control_database', :'control_user') \gexec
SQL

"${SCRIPT_DIR}/migrate-control-plane.sh"
docker compose up -d

echo "NuvoPic is starting at https://nuvopic.app."
echo "Keep ${ENV_FILE} and its SETTINGS_KEK in an encrypted, off-host secret backup."
